
all: figura1-original_EXE figura1-modificado_A_EXE figura1-modificado_B_EXE

figura1-original_EXE: figura1-original.c
	gcc -O2 -o $@ $<

figura1-modificado_A_EXE: figura1-modificado_A.c
	gcc -O2 -o $@ $<

figura1-modificado_B_EXE: figura1-modificado_B.c
	gcc -O2 -o $@ $<
