
private-clauseModificado_a_EXE: private-clauseModificado_a.c
	gcc -O2 -fopenmp -o $@ $<

private-clauseModificado_b_EXE: private-clauseModificado_b.c
	gcc -O2 -fopenmp -o $@ $<

private-clauseModificado_c_EXE: private-clauseModificado_c.c
	gcc -O2 -fopenmp -o $@ $<
