
all: pmm-secuencial_EXE pmm-secuencial-modificado_A_EXE pmm-secuencial-modificado_B_EXE

pmm-secuencial_EXE: pmm-secuencial.c
	gcc -O2 -o $@ $<

pmm-secuencial-modificado_A_EXE: pmm-secuencial-modificado_A.c
	gcc -O2 -o $@ $<

pmm-secuencial-modificado_B_EXE: pmm-secuencial-modificado_B.c
	gcc -O2 -o $@ $<
